# Generated by Django 5.2.1 on 2025-05-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedthread',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='generatedthread',
            name='style',
            field=models.CharField(choices=[('informative', '💡 정보형'), ('funny', '😆 유머형'), ('motivational', '🔥 동기부여형'), ('story', '📖 스토리형')], max_length=100),
        ),
    ]
