# Generated by Django 5.2.1 on 2025-05-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_generatedthread_views_alter_generatedthread_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedthread',
            name='requirements',
            field=models.TextField(blank=True, help_text='추가적인 세부 요건 (선택사항)'),
        ),
        migrations.AddField(
            model_name='generatedthread',
            name='revised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedthread',
            name='revised_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedthread',
            name='revision_prompt',
            field=models.TextField(blank=True, help_text='수정을 위한 피드백'),
        ),
        migrations.AlterField(
            model_name='generatedthread',
            name='style',
            field=models.CharField(choices=[('informative', '정보형'), ('funny', '유머형'), ('motivational', '동기부여형'), ('story', '스토리형')], max_length=100),
        ),
    ]
