# Generated by Django 5.2.1 on 2025-05-12 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_generatedthread_requirements_generatedthread_revised_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedthread',
            name='copies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedthread',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedthread',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='thread_id',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='CopyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copied_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_logs', to='generator.generatedthread')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('like', '좋아요'), ('dislike', '싫어요')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_feedback', to='generator.generatedthread')),
            ],
            options={
                'unique_together': {('thread', 'ip_address')},
            },
        ),
    ]
