services:
  - type: web
    name: thread-generator
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd thread_generator && gunicorn thread_generator.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: thread-generator-db
          property: connectionString

databases:
  - name: thread-generator-db
    databaseName: thread_generator
    user: thread_generator
    plan: free
    ipAllowList: [] 