services:
  - type: web
    name: thread-generator
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --config gunicorn_config.py wsgi_app:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: thread-generator-db
          property: connectionString
      - key: PYTHONPATH
        value: ".:/opt/render/project/src:/opt/render/project/src/thread_generator"
      - key: DJANGO_SETTINGS_MODULE
        value: "thread_generator.settings"

databases:
  - name: thread-generator-db
    databaseName: thread_generator
    user: thread_generator
    plan: free
    ipAllowList: [] 